name: Continuous Integration
on:
  push:
    branches:
      - master
                       # Will make the workflow run every time you push to master

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: build       # Name of step
      run: dotnet build # Command to run

    - name: test       # Name of step
      run: dotnet test # Command to run

    - name: npm install       # Name of step
      run: |
        cd DotnetTemplate.Web
        npm install

    - name: npm build
      run: npm run build
      working-directory: DotnetTemplate.Web

    - name: npm t
      run: npm t
      working-directory: DotnetTemplate.Web

    - name: npm lint runner
      run: npm run lint
      working-directory: DotnetTemplate.Web
  
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: anniebedford/dotnettemplate:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}